#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Final comprehensive Chinese to English translation for gui.py"""

with open('gui.py', 'r', encoding='utf-8') as f:
    content = f.read()

# Final batch of translations
final_translations = {
    '# 半透明气泡': '# Transparent bubble',
    '# Theme配置': '# Theme configuration',
    '"预览设置: 幻灯片数=%s, 当前索引=%s, 尺寸=%s, 缩放=%s"': '"Preview Settings: slides=%s, current index=%s, size=%s, zoom=%s"',
    '# Simplified implementation：水平或垂直渐变': '# Simplified implementation: horizontal or vertical gradient',
    '# Radial gradient（简化实现）': '# Radial gradient (simplified implementation)',
    '"背景图片绘制Failed: %s"': '"Background image rendering failed: %s"',
    '# Canvas does not directly support rotation，这里仅作标记': '# Canvas does not directly support rotation, just as a mark',
    '"🖼️ 图片"': '"🖼️ Image"',
    '"图片渲染Failed: %s"': '"Image rendering failed: %s"',
    '# Delegate to internal logic（如果支持），否则退化': '# Delegate to internal logic (if supported), otherwise fallback',
    '# 深拷贝并解析颜色（支持主题变量 $primary 等），防止 PIL 出现 unknown color specifier': '# Deep copy and parse colors (supports theme variables like $primary), prevent PIL unknown color specifier',
    '# Fallback to original data（Failed时仍尝试渲染）': '# Fallback to original data (still try to render on failure)',
    '"图表渲染Failed: {e}"': '"Chart rendering failed: {e}"',
    'f"{icon}\\n{chart_type.title()} Chart\\n(预览)"': 'f"{icon}\\n{chart_type.title()} Chart\\n(Preview)"',
    'f"元素渲染Failed: type={elem_type}, error={e}"': 'f"Element rendering failed: type={elem_type}, error={e}"',
    '"没有幻灯片"': '"No slides"',
    '# Show transition information（如果有）': '# Show transition information (if any)',
    '"📝 添加幻灯片以查看预览"': '"📝 Add slides to see preview"',
    '"切换到下一页: 索引=%s"': '"Switch to next page: index=%s"',
    '"切换到上一页: 索引=%s"': '"Switch to previous page: index=%s"',
    '"✨ JSON → PPT Designer (增强版)"': '"✨ JSON → PPT Designer (Enhanced)"',
    '# Set application icon（如果可能）': '# Set application icon (if possible)',
    '"📝 JSON 编辑器"': '"📝 JSON Editor"',
    '"🔍 查找"': '"🔍 Find"',
    '"↩️ 撤销"': '"↩️ Undo"',
    '"👁️ 实时预览"': '"👁️ Live Preview"',
    '"适应"': '"Fit"',
    '["50%", "75%", "100%", "125%", "150%", "适应"]': '["50%", "75%", "100%", "125%", "150%", "Fit"]',
    '"📂 打开"': '"📂 Open"',
    '"💾 保存"': '"💾 Save"',
    '"📄 新建"': '"📄 New"',
    '"🎯 格式化"': '"🎯 Format"',
    '"✅ 验证"': '"✅ Validate"',
    '"🎨 主题"': '"🎨 Theme"',
    '# 导出操作': '# Export operations',
    '"📤 导出PPT"': '"📤 Export PPT"',
    '"🖼️ 导出图片"': '"🖼️ Export Images"',
    '"📚 模板"': '"📚 Templates"',
    '"❓ 帮助"': '"❓ Help"',
    '"行 1, 列 1"': '"Line 1, Column 1"',
    '# 编辑器位置更新': '# Editor position update',
    'f"行 {line}, 列 {int(col) + 1}"': 'f"Line {line}, Column {int(col) + 1}"',
    '"✅ JSON 有效"': '"✅ JSON Valid"',
    'f"JSON 语法Error: 第{exc.lineno}行 - {exc.msg}"': 'f"JSON Syntax Error: line {exc.lineno} - {exc.msg}"',
    'f"验证Failed: {exc}"': 'f"Validation Failed: {exc}"',
    '# 错误图标和消息': '# Error icon and message',
    '# 提示Information': '# Tip information',
    '"💡 提示：检查JSON格式，确保所有引号、逗号和括号正确"': '"💡 Tip: Check JSON format, ensure all quotes, commas and brackets are correct"',
    '("新建文件", "当前文件已修改，是否保存？")': '("New File", "Current file has been modified. Save?")',
    '"✨ JSON 已格式化"': '"✨ JSON Formatted"',
    'f"格式化Failed: {exc}"': 'f"Format Failed: {exc}"',
    'f"JSON 验证通过！\\n\\n"': 'f"JSON Validation Passed!\\n\\n"',
    'f"📊 统计Information：\\n"': 'f"📊 Statistics:  \\n"',
    'f"• 幻灯片数量：{slides_count}\\n"': 'f"• Number of slides: {slides_count}\\n"',
    'f"• 元素总数：{elements_count}\\n"': 'f"• Total elements: {elements_count}\\n"',
    'f"• 文件大小：{len(content)} 字符"': 'f"• File size: {len(content)} characters"',
    '"✅ JSON 验证通过"': '"✅ JSON Validation Passed"',
    '("验证Success", message)': '("Validation Passed", message)',
    'f"验证Failed: {exc}"': 'f"Validation Failed: {exc}"',
    '("验证Failed", str(exc))': '("Validation Failed", str(exc))',
    '("选择JSON文件",)': '("Select JSON file",)',
    '[("JSON文件", "*.json"), ("所有文件", "*.*")]': '[("JSON files", "*.json"), ("All files", "*.*")]',
    'f"✅ 已加载: {os.path.basename(file_path)}"': 'f"✅ Loaded: {os.path.basename(file_path)}"',
    '("打开文件Failed", f"JSON格式错误：{e}")': '("Open File Failed", f"JSON format error: {e}")',
    '("打开文件Failed", str(exc))': '("Open File Failed", str(exc))',
    '("保存JSON文件",)': '("Save JSON file",)',
    '[("JSON文件", "*.json")]': '[("JSON files", "*.json")]',
    'f"✅ 已保存: {os.path.basename(file_path)}"': 'f"✅ Saved: {os.path.basename(file_path)}"',
    '("保存Failed", "JSON格式错误，请先修复错误后再保存")': '("Save Failed", "JSON format error, please fix errors first")',
    '("保存Failed", str(exc))': '("Save Failed", str(exc))',
    '("导出PPT", "请先修复JSON错误。")': '("Export PPT", "Please fix JSON errors first.")',
    '("导出PPT文件",)': '("Export PPT file",)',
    '[("PowerPoint文件", "*.pptx")]': '[("PowerPoint files", "*.pptx")]',
    '"⏳ 正在导出PPT..."': '"⏳ Exporting PPT..."',
    'f"✅ 导出Success: {os.path.basename(file_path)} ({file_size_mb:.2f} MB)"': 'f"✅ Export Success: {os.path.basename(file_path)} ({file_size_mb:.2f} MB)"',
    '("导出Success",': '("Export Success",',
    'f"PPT已Success导出！\\n\\n"': 'f"PPT exported successfully!\\n\\n"',
    'f"📊 文件Information：\\n"': 'f"📊 File Information:\\n"',
    'f"• 幻灯片数量：{slide_count} 页\\n"': 'f"• Number of slides: {slide_count}\\n"',
    'f"• 文件大小：{file_size_mb:.2f} MB\\n"': 'f"• File size: {file_size_mb:.2f} MB\\n"',
    'f"• 保存位置：{file_path}\\n\\n"': 'f"• Save location: {file_path}\\n\\n"',
    'f"是否立即打开文件？"': 'f"Open file immediately?"',
    '("导出Failed")': '("Export Failed")',
    '("导出Failed", f"导出过程中发生错误：\\n{str(exc)}")': '("Export Failed", f"Error during export process:\\n{str(exc)}")',
    '"❌ 导出Failed"': '"❌ Export Failed"',
    '("导出图片", "请先修复JSON错误。")': '("Export Images", "Please fix JSON errors first.")',
    '("选择导出文件夹")': '("Select export folder")',
    '"⏳ 正在导出图片..."': '"⏳ Exporting images..."',
    'f"✅ 已导出 {len(slides)} 张图片到: {folder_path}"': 'f"✅ Exported {len(slides)} images to: {folder_path}"',
    'f"已Success导出 {len(slides)} 张图片！"': 'f"Successfully exported {len(slides)} images!"',
    '("导出图片Failed")': '("Export Images Failed")',
    '("导出Failed", f"导出图片时发生错误：\\n{str(e)}")': '("Export Failed", f"Error while exporting images:\\n{str(e)}")',
    'f"无法打开文件: {e}"': 'f"Cannot open file: {e}"',
    '("🎨 主题编辑器")': '("🎨 Theme Editor")',
    '("主题编辑器",': '("Theme Editor",',
    '("颜色设置",': '("Color Settings",',
    '("选择",': '("Select",',
    '("字体设置",': '("Font Settings",',
    '("标题字体:")': '("Heading Font:")',
    '("正文字体:")': '("Body Font:")',
    '"✅ 主题已应用"': '"✅ Theme Applied"',
    '("应用Failed", str(e))': '("Application Failed", str(e))',
    '("应用主题",': '("Apply Theme",',
    '("📚 模板库")': '("📚 Template Library")',
    '"商务演示"': '"Business Presentation"',
    '"专业的商务演示模板，包含封面、目录、内容页和结尾"': '"Professional business presentation template with cover, TOC, content and ending"',
    '"教育课件"': '"Educational Courseware"',
    '"适合教学使用的课件模板，包含标题页、知识点和练习"': '"Courseware template for teaching with title, concepts and exercises"',
    '"产品介绍"': '"Product Introduction"',
    '"产品展示模板，包含产品特性、对比和价格"': '"Product showcase template with features, comparison and pricing"',
    '"数据报告"': '"Data Report"',
    '"数据分析报告模板，包含各种图表展示"': '"Data analysis report template with various charts"',
    '("使用此模板",': '("Use This Template",',
    '("使用模板", "当前文件已修改，使用模板将覆盖当前内容。是否继续？")': '("Use Template", "Current file has been modified. Use template will overwrite current content. Continue?")',
    'f"✅ 已加载模板: {template[\'name\']}"': 'f"✅ Template Loaded: {template[\'name\']}"',
    '"商务演示标题"': '"Business Presentation Title"',
    '"副标题文字"': '"Subtitle Text"',
    '"课程标题"': '"Course Title"',
    '"产品名称"': '"Product Name"',
    '"数据分析报告"': '"Data Analysis Report"',
    '"销售额"': '"Sales Revenue"',
    '("❓ 帮助")': '("❓ Help")',
    '("快捷键")': '("Shortcuts")',
    
    # Help text blocks
    '键盘快捷键：': 'Keyboard Shortcuts:',
    '文件操作：': 'File Operations:',
    '  Ctrl+N    新建文件': '  Ctrl+N    New File',
    '  Ctrl+O    打开文件': '  Ctrl+O    Open File',
    '  Ctrl+S    保存文件': '  Ctrl+S    Save File',
    '  Ctrl+E    导出PPT': '  Ctrl+E    Export PPT',
    '编辑操作：': 'Edit Operations:',
    '  Ctrl+F    查找': '  Ctrl+F    Find',
    '  Ctrl+Z    撤销': '  Ctrl+Z    Undo',
    '  Ctrl+Y    重做': '  Ctrl+Y    Redo',
    '  F5        刷新预览': '  F5        Refresh Preview',
    '导航操作：': 'Navigation:',
    '  Ctrl+←    上一页': '  Ctrl+←    Previous Page',
    '  Ctrl+→    下一页': '  Ctrl+→    Next Page',
    '  Home      第一页': '  Home      First Page',
    '  End       最后一页': '  End       Last Page',
    '其他：': 'Other:',
    '  Ctrl+H    显示帮助': '  Ctrl+H    Show Help',
    '  Esc       关闭对话框': '  Esc       Close Dialog',
    '("元素类型")': '("Element Types")',
    '支持的元素类型：': 'Supported Element Types:',
    '📝 text - 文本元素': '📝 text - Text Element',
    '   支持样式、段落、列表等': '   Supports styles, paragraphs, lists, etc.',
    '🖼️ image - 图片元素': '🖼️ image - Image Element',
    '   支持本地文件、URL、base64': '   Supports local files, URLs, base64',
    '📊 chart - 图表元素': '📊 chart - Chart Element',
    '   柱状图、折线图、饼图、雷达图等': '   Bar chart, line chart, pie chart, radar chart, etc.',
    '🔷 shape - 形状元素': '🔷 shape - Shape Element',
    '   矩形、圆形、星形、箭头等30+种': '   Rectangle, circle, star, arrow, etc. 30+ types',
    '📋 table - 表格元素': '📋 table - Table Element',
    '   支持样式、条纹行列': '   Supports styles, striped rows and columns',
    '➖ line - 线条元素': '➖ line - Line Element',
    '   支持箭头、曲线': '   Supports arrows, curves',
    '⭐ icon - 图标元素': '⭐ icon - Icon Element',
    '   支持多个图标库': '   Supports multiple icon libraries',
    '👥 group - 组元素': '👥 group - Group Element',
    '   组合多个元素': '   Combine multiple elements',
    '🎬 video - 视频元素': '🎬 video - Video Element',
    '   视频占位符': '   Video placeholder',
    '🎯 smartArt - 智能图形': '🎯 smartArt - SmartArt',
    '   流程图、循环图等': '   Flowchart, circular diagram, etc.',
    '("关于")': '("About")',
    
    '一个强大的JSON到PowerPoint转换工具，支持：': 'A powerful JSON to PowerPoint conversion tool that supports:',
    '• 实时预览': '• Real-time preview',
    '• 丰富的元素类型': '• Rich element types',
    '• 主题系统': '• Theme system',
    '• 渐变和阴影效果': '• Gradient and shadow effects',
    '• 多种图表类型': '• Multiple chart types',
    '• 智能图形': '• SmartArt',
    '作者：AI Assistant': 'Author: AI Assistant',
    '许可：MIT License': 'License: MIT License',
    '感谢使用！': 'Thank you for using!',
    
    '("查找")': '("Find")',
    '("查找内容:")': '("Find:")',
    '("查找", command=do_find)': '("Find", command=do_find)',
}

for old, new in final_translations.items():
    content = content.replace(old, new)

with open('gui.py', 'w', encoding='utf-8') as f:
    f.write(content)

print('Final translation completed!')
