#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Comprehensive Chinese to English translation"""

with open('gui.py', 'r', encoding='utf-8') as f:
    content = f.read()

# Extensive Chinese-to-English translations
translations = {
    '"""绘制水平柱状图"""': '"""Draw horizontal bar chart"""',
    '"""绘制环形图"""': '"""Draw donut chart"""',
    '"""绘制雷达图"""': '"""Draw radar chart"""',
    '"""绘制气泡图"""': '"""Draw bubble chart"""',
    '"""增强的PPT预览组件"""': '"""Enhanced PPT preview component"""',
    '"""设置PPT元数据"""': '"""Set PPT metadata"""',
    '"""解析颜色值，支持主题变量"""': '"""Parse color values, supports theme variables"""',
    '"""创建渐变图像"""': '"""Create gradient image"""',
    '"""渲染背景，支持渐变"""': '"""Render background, supports gradient"""',
    '"""绘制文本，支持阴影和旋转"""': '"""Draw text, supports shadow and rotation"""',
    '"""绘制边框"""': '"""Draw border"""',
    '"""应用旋转（简化实现）"""': '"""Apply rotation (simplified implementation)"""',
    '"""绘制形状，支持更多类型"""': '"""Draw shapes, supports more types"""',
    '"""绘制基本形状"""': '"""Draw basic shapes"""',
    '"""绘制线条元素"""': '"""Draw line element"""',
    '"""绘制箭头头部"""': '"""Draw arrow head"""',
    '"""绘制图标元素"""': '"""Draw icon element"""',
    '"""绘制组元素"""': '"""Draw group element"""',
    '"""绘制视频占位符"""': '"""Draw video placeholder"""',
    '"""绘制SmartArt"""': '"""Draw SmartArt"""',
    '"""绘制图片，支持滤镜"""': '"""Draw image, supports filters"""',
    '"""渲染图表预览"""': '"""Render chart preview"""',
    '"""绘制表格，支持更多样式"""': '"""Draw table, supports more styles"""',
    '"""绘制元素的统一入口"""': '"""Unified entry point for drawing elements"""',
    '"""渲染单个幻灯片"""': '"""Render single slide"""',
    '"""渲染当前幻灯片"""': '"""Render current slide"""',
    '"""切换到下一张幻灯片"""': '"""Switch to next slide"""',
    '"""切换到上一张幻灯片"""': '"""Switch to previous slide"""',
    '"""增强的JSON到PPT设计器应用"""': '"""Enhanced JSON to PPT Designer application"""',
    '"""设置UI样式"""': '"""Set UI style"""',
    '"""设置UI布局"""': '"""Set UI layout"""',
    '"""创建工具栏"""': '"""Create toolbar"""',
    '"""创建状态栏"""': '"""Create status bar"""',
    '"""设置键盘快捷键"""': '"""Set keyboard shortcuts"""',
    '"""更新光标位置显示"""': '"""Update cursor position display"""',
    '"""更新行号显示"""': '"""Update line number display"""',
    '"""同步编辑器和行号的滚动"""': '"""Sync editor and line number scrolling"""',
    '"""加载示例JSON"""': '"""Load sample JSON"""',
    '"""编辑器内容修改事件"""': '"""Editor content modification event"""',
    '"""安排渲染（防抖）"""': '"""Schedule rendering (debounce)"""',
    '"""刷新预览"""': '"""Refresh preview"""',
    '"""高亮错误行"""': '"""Highlight error line"""',
    '"""清除错误高亮"""': '"""Clear error highlight"""',
    '"""显示错误Information"""': '"""Show error information"""',
    '"""设置状态栏消息"""': '"""Set status bar message"""',
    '"""新建文件"""': '"""New file"""',
    '"""格式化JSON"""': '"""Format JSON"""',
    '"""验证JSON"""': '"""Validate JSON"""',
    '"""打开文件"""': '"""Open file"""',
    '"""保存文件"""': '"""Save file"""',
    '"""导出PPT文件"""': '"""Export PPT file"""',
    '"""导出为图片"""': '"""Export as image"""',
    '"""在系统中打开文件"""': '"""Open file in system"""',
    '"""显示主题编辑器"""': '"""Show theme editor"""',
    '"""选择颜色"""': '"""Select color"""',
    '"""显示模板库"""': '"""Show template library"""',
    '"""使用模板"""': '"""Use template"""',
    '"""获取商务模板"""': '"""Get business template"""',
    '"""获取教育模板"""': '"""Get education template"""',
    '"""获取产品模板"""': '"""Get product template"""',
    '"""获取数据模板"""': '"""Get data template"""',
    '"""显示帮助"""': '"""Show help"""',
    '"""在编辑器中查找"""': '"""Find in editor"""',
    '"""撤销编辑"""': '"""Undo edit"""',
    '"""下一页"""': '"""Next page"""',
    '"""上一页"""': '"""Previous page"""',
    '"""第一页"""': '"""First page"""',
    '"""最后一页"""': '"""Last page"""',
    '"""缩放变化"""': '"""Zoom change"""',
    '"""更新幻灯片Information"""': '"""Update slide information"""',
    '"""主函数"""': '"""Main function"""',
    
    # Simple comments and strings
    '# 分类标签': '# Category label',
    '# 外圈': '# Outer circle',
    '# 内圈（挖空）': '# Inner circle (hollow)',
    '# 绘制网格': '# Draw grid',
    '# 绘制多边形网格': '# Draw polygon grid',
    '# 绘制轴线和标签': '# Draw axes and labels',
    '# 标签': '# Labels',
    '# 绘制数据': '# Draw data',
    '# 半透明填充': '# Transparent fill',
    '# 绘制边框': '# Draw border',
    '# 收集所有数据点': '# Collect all data points',
    '# 计算范围': '# Calculate range',
    '# 绘制气泡': '# Draw bubbles',
    '# 坐标轴': '# Axes',
    '# X轴标签': '# X-axis labels',
    '# 绘制线条': '# Draw lines',
    '# 绘制线': '# Draw line',
    '# 闭合区域': '# Close area',
    '# 渲染背景': '# Render background',
    '# 获取所有元素并按zIndex排序': '# Get all elements and sort by zIndex',
    '# 渲染所有元素': '# Render all elements',
    '# 显示过渡效果Information': '# Show transition information',
    '# 在角落显示过渡效果标记': '# Show transition mark in corner',
    '# 简化实现': '# Simplified implementation',
    '# 水平或垂直渐变': '# Horizontal or vertical gradient',
    '# 找到对应的颜色区间': '# Find corresponding color range',
    '# 在两个停止点之间插值': '# Interpolate between two stops',
    '# 径向渐变': '# Radial gradient',
    '# 找到对应的颜色': '# Find corresponding color',
    '# 创建阴影层': '# Create shadow layer',
    '# 应用模糊': '# Apply blur',
    '# 合成': '# Composite',
    '# 优先渐变，其次纯色': '# Prefer gradient, otherwise solid color',
    '# 应用透明度': '# Apply transparency',
    '# 应用滤镜': '# Apply filter',
    '# 背景图片绘制Failed': '# Background image rendering failed',
    '# 处理段落': '# Handle paragraphs',
    '# 文本阴影': '# Text shadow',
    '# 主文本': '# Main text',
    '# Canvas不直接支持旋转': '# Canvas does not directly support rotation',
    '# Gradient填充': '# Gradient fill',
    '# 绘制阴影形状': '# Draw shadow shape',
    '# 主形状': '# Main shape',
    '# 五角星': '# Pentagon star',
    '# 默认五角星': '# Default pentagon star',
    '# 简化的心形': '# Simplified heart shape',
    '# 十字': '# Cross',
    '# 默认矩形': '# Default rectangle',
    '# 转换点坐标': '# Convert point coordinates',
    '# 箭头': '# Arrow',
    '# 绘制箭头': '# Draw arrow',
    '# 计算箭头两个点': '# Calculate two arrow points',
    '# 使用形状模拟图标': '# Use shape to simulate icon',
    '# 绘制一个简单的星形作为图标': '# Draw a simple star as icon',
    '# 递归绘制子元素': '# Recursively draw sub-elements',
    '# 绘制视频占位符': '# Draw video placeholder',
    '# 播放按钮': '# Play button',
    '# 三角形播放图标': '# Triangle play icon',
    '# 列表或流程图': '# List or flowchart',
    '# 节点颜色': '# Node color',
    '# 绘制节点': '# Draw node',
    '# 节点文本': '# Node text',
    '# 连接线': '# Connection line',
    '# 循环图': '# Circular diagram',
    '# 占位符': '# Placeholder',
    '# 应用滤镜': '# Apply filter',
    '# 简单的棕褐色效果': '# Simple sepia effect',
    '# 图片渲染Failed': '# Image rendering failed',
    '# 兼容别名 -> 内部实际渲染类型': '# Alias compatibility -> internal actual rendering type',
    '# 使用折线 + fill 模拟': '# Simulate with line + fill',
    '# 交给内部逻辑': '# Delegate to internal logic',
    '# 解析直接颜色': '# Parse direct color',
    '# 解析渐变颜色 stops': '# Parse gradient color stops',
    '# 退回原始数据': '# Fallback to original data',
    '# 使用增强的图表渲染器': '# Use enhanced chart renderer',
    '# 图表渲染Failed': '# Chart rendering failed',
    '# 显示占位符': '# Show placeholder',
    '# 表格样式': '# Table style',
    '# 单元格背景色': '# Cell background color',
    '# 表头': '# Header',
    '# 表体': '# Body',
    '# 获取总行数': '# Get total lines',
    '# 更新行号': '# Update line numbers',
    '# 同步滚动': '# Sync scrolling',
    '# 先验证JSON格式': '# Validate JSON format first',
    '# 保存当前文件路径': '# Save current file path',
    '# 如果有当前文件路径，直接保存': '# If have current file path, save directly',
    '# 验证JSON格式': '# Validate JSON format',
    '# 临时切换到该幻灯片并渲染': '# Temporarily switch to slide and render',
    '# 获取canvas内容并保存为图片': '# Get canvas content and save as image',
    '# 保存图片': '# Save image',
    '# 恢复原来的幻灯片': '# Restore original slide',
    '# 导出图片Failed': '# Export image failed',
    '# 简单的主题编辑界面': '# Simple theme editor interface',
    '# Color设置': '# Color settings',
    '# 获取当前主题': '# Get current theme',
    '# Color预览': '# Color preview',
    '# Font设置': '# Font settings',
    '# 应用按钮': '# Apply button',
    '# 更新主题到当前JSON': '# Update theme to current JSON',
    '# 更新编辑器': '# Update editor',
    '# 模板列表': '# Template list',
    '# 创建模板网格': '# Create template grid',
    '# 模板预览': '# Template preview',
    '# 模板名称': '# Template name',
    '# 模板描述': '# Template description',
    '# 使用按钮': '# Use button',
    '# 配置网格权重': '# Configure grid weights',
    '# 创建notebook': '# Create notebook',
    '# 快捷键页面': '# Shortcuts page',
    '# 元素类型页面': '# Element types page',
    '# 关于页面': '# About page',
    '# 清除之前的高亮': '# Clear previous highlight',
    '# 搜索文本': '# Search text',
    '# 配置高亮样式': '# Configure highlight style',
    '# 跳转到第一个匹配': '# Jump to first match',
    '# 绑定回车键': '# Bind enter key',
    '# 恢复自适应缩放': '# Restore adaptive scaling',
    '# 设置固定缩放': '# Set fixed scaling',
    '# 设置DPI感知': '# Set DPI awareness',
    '# 设置应用图标': '# Set application icon',
    '# 居中窗口': '# Center window',
    '# 基础样式': '# Base style',
    '# 按钮样式': '# Button style',
    '# 左侧编辑器': '# Left editor',
    '# 编辑器工具栏': '# Editor toolbar',
    '# 行号显示': '# Line numbers',
    '# JSON编辑器': '# JSON editor',
    '# 右侧预览': '# Right preview',
    '# 导航控制': '# Navigation control',
    '# 缩放控制': '# Zoom control',
    '# 文件操作': '# File operations',
    '# 编辑操作': '# Edit operations',
    '# 右侧快捷操作': '# Right quick actions',
    '# 编码Information': '# Encoding information',
    '# 位置Information': '# Position information',
    '# 记录错误行号': '# Record error line number',
    '# 创建主分割面板': '# Create main split panel',
    '# 可以添加颜色变化效果': '# Can add color change effect',
    '# 保存当前光标位置': '# Save current cursor position',
    '# 尝试恢复光标位置': '# Try to restore cursor position',
    '# 统计Information': '# Statistics information',
    '# 打开文件Failed': '# Open file failed',
    '# 插入基础模板': '# Insert base template',
    '# 主题': '# Theme',
    '# 模板': '# Templates',
    '# 帮助': '# Help',
    '# 导出PPT': '# Export PPT',
    '# 导出图片': '# Export image',
    '# 无法打开文件': '# Cannot open file',
    '# 当前文件已修改': '# Current file has been modified',
    '# 是否继续': '# Continue',
    '# 当前文件已修改，使用模板将覆盖当前内容。是否继续？': '# Current file has been modified, using template will overwrite current content. Continue?',
    '# 选择JSON文件': '# Select JSON file',
    '# JSON文件': '# JSON files',
    '# 所有文件': '# All files',
    '# 选择导出文件夹': '# Select export folder',
    '# 是否立即打开文件': '# Open file immediately?',
    '# 选择': '# Select',
    '# 商务演示': '# Business Presentation',
    '# 专业的商务演示模板，包含封面、目录、内容页和结尾': '# Professional business presentation template with cover, table of contents, content pages and ending',
    '# 教育课件': '# Educational Courseware',
    '# 适合教学使用的课件模板，包含标题页、知识点和练习': '# Courseware template suitable for teaching, including title page, knowledge points and exercises',
    '# 产品介绍': '# Product Introduction',
    '# 产品展示模板，包含产品特性、对比和价格': '# Product showcase template with features, comparison and pricing',
    '# 数据报告': '# Data Report',
    '# 数据分析报告模板，包含各种图表展示': '# Data analysis report template with various chart displays',
    '# 当前文件已修改，是否保存？': '# Current file has been modified. Save?',
    '# 标题字体': '# Heading font',
    '# 正文字体': '# Body font',
}

for old, new in translations.items():
    content = content.replace(old, new)

with open('gui.py', 'w', encoding='utf-8') as f:
    f.write(content)

print('Translation complete!')
